site_name: PnP Modern Search
nav:
    - Home: index.md
    - Versions: version.md
    - Contributors: contributors.md
    - Building documentation: build-the-doc.md
    - Web Parts: 
      - Getting started: search-parts/getting-started.md
      - Search Box: search-parts/search-box.md
      - Search Results: search-parts/search-results.md
      - Search Refiners: search-parts/search-refiners.md
      - Search Pagination: search-parts/search-pagination.md
      - Search Navigation: search-parts/search-navigation.md
      - Search Verticals: search-parts/search-verticals.md
      - Templating: search-parts/templating.md
    - Extensibility Library: 
      - Getting started: search-extensibility-library/getting-started.md
    - Custom Renderer: 
      - Getting Started: search-custom-renderer/getting-started.md
    - Search Query Enhancer:
      - Getting started: search-query-enhancer/getting-started.md
      - Debug locally: search-query-enhancer/debug-locally.md
theme:
  name: 'material'
  palette:
    primary: 'orange'
  feature:
    tabs: true
extra_css:
  - 'extra.css'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
extra:
  social:
    - type: 'twitter'
      link: 'https://twitter.com/officedevpnp'
    - type: 'youtube'
      link: 'http://aka.ms/sppnp-videos'
    - type: 'link'
      link: 'https://aka.ms/sppnp'
repo_url: https://github.com/microsoft-search/pnp-modern-search
edit_uri: blob/master/docs